version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: weatherapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: eutenhoexp0
      MYSQL_DATABASE: weatherapp
    ports:
      - "3309:3306"


